[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.117.0"

[context.production.environment]
  HUGO_VERSION = "0.121.0"
  RUBY_VERSION = "3.2.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.117.0"